export const settingsSlider = {
  dots: false,
  className: "center",
  centerMode: true,
  infinite: true,
  centerPadding: "0px",
  slidesToShow: 5,
  speed: 500,
  rows: 2,
  slidesPerRow: 1,
  autoplaySpeed: 2000,
  autoplay: true,
  cssEase: "linear",
  arrows: true,
}
