export { default as AdminLayout } from "./admin.layout"
export { default as AuthLayout } from "./auth.layout"
export { default as AuthSellerLayout } from "./authSeller.layout"
export { default as MainLayout } from "./main.layout"
export { default as SellerLayout } from "./seller.layout"
export { default as ProfileLayout } from "./profile.layout"
